[package]
name = "rocket_test"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
diesel = { version = "1.4.4", features = ["postgres"] }
rocket = "0.5.0-rc.1"
serde = "1.0.136"
serde_json = "1.0.78"
