services:
  db:
    image: postgres:12.9
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "8001:5432"
  rocket_pg_template:
    build: .
    depends_on:
     - db
    environment:
      - DATABASE_URL=postgres://username:password@db/postgres
    ports:
      - "8000:8000"