### Health check
GET http://127.0.0.1:8000/api/health_check

### Register
POST http://localhost:8000/api/users/register
Content-Type: application/x-www-form-urlencoded

username=odd
&email=odd@test.com
&password=my_secure_password

### Login
POST http://localhost:8000/api/users/login
Content-Type: application/x-www-form-urlencoded

username=odd
&password=my_secure_password

### Get logged in user
GET http://localhost:8000/api/users/me

### Create problem
POST http://localhost:8000/api/problems
Content-Type: application/x-www-form-urlencoded

title=First Problem
&grade=4

### Get all problems
GET http://localhost:8000/api/problems

### Get problem by id
GET http://localhost:8000/api/problems/1

### Edit problem by id
PUT http://localhost:8000/api/problems/1
Content-Type: application/x-www-form-urlencoded

title=Updated Problem
&grade=4

### Delete problem by id
DELETE http://localhost:8000/api/problems/1

### Logout
POST http://localhost:8000/api/users/logout